### ISSUE TITLE
Free Managed Certificates support

### ISSUE THREAD

**Issue by JoaoFHS** [Azure/terraform-azurerm-avm-res-app-containerapp#39]
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Container App supports the creation of a custom domain with [free managed certificates](https://learn.microsoft.com/en-us/azure/container-apps/custom-domains-managed-certificates?pivots=azure-portal). To make this work one of the scenarios below must be met for domain validation:

- A CNAME record and a TXT record with the Custom Domain Verification ID of the container app registered in a valid DNS Zone.
- An A record and a TXT record with the Custom Domain Verification ID of the container app in a valid DNS Zone.

Because of this requirement, the order of creation must be:

1. Container app (since this is the resource that exports the  Custom Domain Verification ID required for the TXT record)
2. Creation of the records in my DNS Zone
3. Creation of the custom domain with free managed certificates.

With that said, it looks to me that it isn't possible to use custom domains with managed certificates while using the container app AVM module, or am I missing something? If that's the case, shouldn't the [azurerm_container_app_custom_domain](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_app_custom_domain) resource be managed outside the module?

**Comment by lonegunmanb** [comment]
Hi @JoaoFHS sorry for the late reply, I've opened a pr #48 for this, now you can create `azurerm_container_app_environment_certificate` by using `var.container_app_environment_certificate`, and link the created certificates to custom domains by assigning the same key to new `container_app_environment_certificate_key` field in `var.custom_domains`. Could this pr solve your issue?
