### ISSUE TITLE
[AVM Module Issue]: Missing azure/modtm in required_providers

### ISSUE THREAD

**Issue by alefteris** [Azure/terraform-azurerm-avm-res-app-containerapp#55]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Bug

### (Optional) Module Version

master

### Description

The azure/modtm provider is missing in required_providers in the master branch, after an automatic change was applied to the repo.

**Comment by lonegunmanb** [comment]
I'm closing this issue since it has been solved.
